### ISSUE TITLE
Entering non numberic value to fov command closes app

### ISSUE THREAD

**Issue by Limited55** [theTwist84/Twisters-H5F-Console-Tool#1]
So when I enter `fov test` the application closes without saying why. You should log a message saying enter a number and not close.

**Comment by twist84** [comment]
Fixed in [def46713c3ab5f8ded0866755ce772168ffa00ba](https://github.com/theTwist84/Twisters-H5F-Console-Tool/commit/def46713c3ab5f8ded0866755ce772168ffa00ba)
